### ISSUE TITLE
method similar to rails' content_for

### ISSUE THREAD

**Issue by andrewzah** [kemalyst/kemalyst#11]
http://api.rubyonrails.org/classes/ActionView/Helpers/CaptureHelper.html

This lets one do something similar to 

```ecr
# post/show.ecr
<% content_for(:title, "About") %>
```

It's also useful for generating Meta tags per post:  

```ecr
# layouts/main.ecr
<meta 
  property="og:title" 
  content="<%= content_for?(:title) ? yield(:title) : "Default"
/>
```

How tough would this be to implement in Kemalyst?

**Comment by drujensen** [comment]
not sure how hard it would be.  I will look into it.

**Comment by drujensen** [comment]
One way to handle this:
```
# post/show.ecr
<% context.params["title"] = "About" %>
```
and then in the layout:
```
# layouts/main.ecr
<title><%= context.params["title"]? || "Default" %></title>
```
