### ISSUE TITLE
Chaining is not put back to a clean state after routing

### ISSUE THREAD

**Issue by TechMagister** [kemalyst/kemalyst#15]
TL;TR : after processing request ( Router#process_request ) the handler.next pointer should be reset to nil for each route, if not, the chaining stay in place and produce unexpected behaviors.

The test case to reproduce this is a little complex : 
```crystal
class TestHandler < Kemalyst::Controller
  def call(ctx)
    return call_next(ctx) unless self.next.nil?
    "All"
  end
end
```
```crystal
  it "process_request and clean state" do 
    router = Kemalyst::Handler::Router.new
    handler0 = TestHandler.new
    handler1 = Kemalyst::Handler::Block.new(->(c : HTTP::Server::Context) { "Dashboard" })
    
    router.add_route("GET", "/*", handler0)
    router.add_route("GET", "/dashboard", handler1)

    request = HTTP::Request.new("GET", "/dashboard")
    io, context = create_context(request)
    router.call(context)
    context.response.close
    io.rewind
    client_response = HTTP::Client::Response.from_io(io, decompress: false)
    client_response.body.should eq "Dashboard"

    request = HTTP::Request.new("GET", "/404")
    io, context = create_context(request)
    router.call(context)
    context.response.close
    io.rewind
    client_response = HTTP::Client::Response.from_io(io, decompress: false)
    client_response.body.should eq "All"

  end
```
I got : 
```
1) Kemalyst::Handler::Router process_request and clean state
     Failure/Error: client_response.body.should eq "All"

       expected: "All"
            got: "Dashboard"
```

A way to fix it is by adding this code before returning context into the Router#process_request method : 
```crystal
      # clean state
      routes.each do |route|
        route.handler.next = nil if route
      end
```

**Comment by drujensen** [comment]
@TechMagister Thanks for reporting this.  

The use case of using the "/*" was never intended to be the used as the last endpoint in a chain.   It was to allow to easily add other handlers before a set of endpoint handlers.

I am afraid we will have race conditions using it in this manner.  I will take a look when I get a chance.

**Comment by drujensen** [comment]
@TechMagister I created a PR with this change.  Can you take a look when you get a chance? https://github.com/drujensen/kemalyst/pull/16

**Comment by drujensen** [comment]
I need to refactor this.  I believe there is a possibility of a chance of a race condition the way it's currently built.

**Comment by drujensen** [comment]
created a new ticket to address the possible race condition.
