### ISSUE TITLE
Rails like command line

### ISSUE THREAD

**Issue by TechMagister** [kemalyst/kemalyst#17]
It can be useful to add a rails like command line to:

- Have a REPL ( icr )
- Generate Controllers/Models/...
- Run sentry ( configured to watch the changes of config files, and no need to keep it in ./dev folder )
- Run db console according to ./config/database.yml
- Run database migration ( db/migrate.cr )

I see it this way : 
During the post install of kemalyst ( or by adding something like kemalyst-generator to development_dependencies ), it build a binary into {PROJECT_ROOT}/dev/kgen ( and add it to .gitignore )

```
$ ./dev/kgen console #=> icr
$ ./dev/kgen generate model NAME [field[:type][:index] field[:type]  #=> get adapter from ./config/database.yml
$ ./dev/kgen generate controller NAME [action action]
$ ./dev/kgen watch #=> run a configured instance of sentry
$ ./def/kgen db  #=> run database client according to ./config/database.yml configuration
$ ./dev/kgen db:migrate
```

And so on
( perhaps it could be better to create a kemalyst-generator in a separate project if it has to do so much things ☕️  )

**Comment by drujensen** [comment]
:+1:   What do you think about using /bin instead of /dev?

**Comment by TechMagister** [comment]
Yes, it'll be semantically better.
There is a shards branch to allow installing binaries ( https://github.com/crystal-lang/shards/pull/126 ) it should be taken in account.

I'm currently working on another project ( https://github.com/TechMagister/cracker ) but once I'm done with it I'll focus on this one.

**Comment by TechMagister** [comment]
Started here : https://github.com/TechMagister/kemalyst-generator

**Comment by drujensen** [comment]
This is now a reality.  Thanks @TechMagister !
