### ISSUE TITLE
Leverage DB::Mapping macro

### ISSUE THREAD

**Issue by drujensen** [kemalyst/kemalyst#18]
Look into leveraging the DB::Mapping macro.  Extend the mapping method to provide a database type to work with migrations.

http://crystal-lang.github.io/crystal-db/api/0.3.2/DB.html#mapping

**Comment by TechMagister** [comment]
Why not using [crecto](https://github.com/fridgerator/crecto) and [micrate](https://github.com/juanedi/micrate) for database mapping ?

Crecto provides validation and query syntax and micrate allow to easily customize tables ( while giving an history of modifications ).

Both can easily be embedded/used with the future #17 and having less dedicated dependencies may reduce the workload ?

What do you think ?

**Comment by drujensen** [comment]
@TechMagister Thanks for the recommendation.   

I may have been too aggressive with my vision of having a declarative way to specify the database schema without requiring migration scripts.

If we move to migration scripts, we can use DB::Mapping without modification.  It would simplify the adapters and reduce the codebase significantly in the kemalyst-models.  Also, as you stated, its inline with the rails way and would work well with a command line tool.

I will take a closer look at the two projects.

**Comment by drujensen** [comment]
I have moved the migration to use `micrate`.   Thanks for the recommendation.
