### ISSUE TITLE
Error resolving db (~> 0.3.0, ~> 0.4.0)

### ISSUE THREAD

**Issue by elorest** [kemalyst/kemalyst#29]
All of the database adapters now point to db 0.4.0. But kemalyst model still points to versions of adapters with old versions of db. However, in a kemalyst project if I include crystal-lang/mysql it conflicts because db is 0.4.0 and kemalyst model is requiring older versions of db.

I fixed this on my project be forking both kemalyst and kemalyst-model. I ended up having to delete the shard.lock file from both of those projects so I don't want to submit a pull request right now but everything seems to work.

**Comment by drujensen** [comment]
Ok. Thanks for letting me know. I will update them.

**Comment by elorest** [comment]
Thanks.

**Comment by drujensen** [comment]
done!
