### ISSUE TITLE
params for input type file, just shows filename.

### ISSUE THREAD

**Issue by elorest** [kemalyst/kemalyst#37]
How would I access the content and mime types of uploaded files?

**Comment by drujensen** [comment]
Look at using this:  https://crystal-lang.org/api/0.22.0/HTTP/FormData.html.  I've never attempted using it yet.

**Comment by elorest** [comment]
Would I add that into params.cr?

**Comment by drujensen** [comment]
You could but I would consider creating a new handler and add the file info to the context.

**Comment by elorest** [comment]
Ok.

**Comment by elorest** [comment]
Where is the order or handlers set. I'm seeing `call_next(context)` all over the place. How do I know what's next or set that?

**Comment by drujensen** [comment]
@elorest the list of handlers is configurable in the `config/application.cr`.  The default list is configured here: https://github.com/drujensen/kemalyst/blob/master/src/kemalyst.cr#L45

**Comment by drujensen** [comment]
@elorest if you have time, a spec hitting the `multipart` content_type would be good to have.

**Comment by elorest** [comment]
Yeah i was meaning to add specs.

On Apr 23, 2017 10:47 AM, "Dru Jensen" <notifications@github.com> wrote:

@elorest <https://github.com/elorest> if you have time, a spec hitting the
multipart content_type would be good to have.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/drujensen/kemalyst/issues/37#issuecomment-296456227>,
or mute the thread
