### ISSUE TITLE
how can i create a app without database connection ?

### ISSUE THREAD

**Issue by luizamboni** [kemalyst/kemalyst#55]
Is possible ?

**Comment by drujensen** [comment]
Hi @luizamboni Thanks for trying out Kemalyst.

I have joined forces with the Amber team and we have moved most of the functionality of Kemalyst over to that project.  You will find it quite similar to Kemalyst but has improvements on the routing in that Amber supports pipes.

Regarding the app without database, we currently do not have that option for the `kgen init app {name}` but you can remove the shards for the db, kemalyst-model and config/database.yml manually.  There is no dependencies on that.  You can use crecto or other ORM if you wish.

**Comment by luizamboni** [comment]
i created with sqlite and not used this. Only to not need connect with a database.
I m consumming a rest api, not need persistency
