### ISSUE TITLE
crack dependency inside kemalyst

### ISSUE THREAD

**Issue by luizamboni** [kemalyst/kemalyst#56]
i got some error when try run `kgen watch`
"in lib/kemalyst/src/kemalyst.cr:4: while requiring "crack": can't find file 'crack' relative to ..."

I m not found crack lib in dependencies of kemalyst , and i not found too in internet.

How can i resolve this ?

**Comment by drujensen** [comment]
I recommend updating to the latest `kgen` or `amber` command line utility.  I have reverted the changes to use `crack` since it caused a lot of confusion.

**Comment by luizamboni** [comment]
i installad the kgen version as recommended in REAME.md 
"0.6.1"
not is the lasted ?

**Comment by drujensen** [comment]
0.8.0 is the latest kgen version.

can you try `brew update` and `brew upgrade kgen`?

**Comment by luizamboni** [comment]
i m using ubuntu...i m trying clone and replace, but got a problem with key

**Comment by luizamboni** [comment]
`git clone git@github.com:kemalyst/kemalyst-generator.git
Cloning into 'kemalyst-generator'...
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
`

**Comment by drujensen** [comment]
try this:
```
export KGEN_VERSION=0.8.0
curl -L https://github.com/kemalyst/kemalyst-generator/archive/v$KGEN_VERSION.tar.gz | sudo tar xvz -C /usr/local/share/. && cd /usr/local/share/kemalyst-generator-$KGEN_VERSION && sudo crystal deps && sudo make
sudo ln -sf /usr/local/share/kemalyst-generator-$KGEN_VERSION/bin/kgen /usr/local/bin/kgen
```

**Comment by luizamboni** [comment]
works fine, thank you
