### ISSUE TITLE
issue in installing quartz-mailer

### ISSUE THREAD

**Issue by harisr92** [kemalyst/kemalyst#58]
When I try shards install got an error like this
`shard name (quartz_mailer) doesn't match dependency name (quartz-mailer)`
 Can you please tell me why this is happening

Thank you

**Comment by drujensen** [comment]
@harisr92 The repository was renamed to quartz_mailer.

You can update your `shard.yml` to this:
```
  quartz_mailer:
    github: amberframework/quartz-mailer
    version: ~> 0.2.0
```

**Comment by harisr92** [comment]
Thank you. I just updated shard.yml. Now its working fine
