### ISSUE TITLE
Syntax error in ./libs/kemalyst/kemalyst/handler/router.cr:141: expecting token ')', not 'as'

### ISSUE THREAD

**Issue by timolehto** [kemalyst/kemalyst#6]
Hi,

I'm a bit new to crystal and was trying out some of your samples, but I have some difficulties running for example this:
https://github.com/drujensen/chat-kemalyst

I get errors like this from kemalyst:

```
Syntax error in ./libs/kemalyst/kemalyst/handler/router.cr:141: expecting token ')', not 'as'
```

Looking at the [offending line](https://github.com/drujensen/kemalyst/blob/master/src/kemalyst/handler/router.cr#L141):

```
result = lookup_route(method as String, context.request.path)
```

Is this perhaps some old syntax or something? I can see that crystal has this [pseudomethod as](https://crystal-lang.org/docs/syntax_and_semantics/as.html) which one can call like this `foo.as String`, but `foo as String` just seems to be wrong.

**Comment by timolehto** [comment]
Ok actually looking at the latest commit on master I can see that this has just been fixed. It's just that the sample apps shards is still locked to old sha
https://github.com/drujensen/chat-kemalyst/blob/master/shard.lock#L9
https://github.com/drujensen/kemalyst/commit/88555fe7068163a7afd622e2841bca1732314e76

**Comment by timolehto** [comment]
Somehow running example through docker-compose seems to work, though it looks like the docker image is using the latest crystal version 0.19.4 O.o

**Comment by drujensen** [comment]
@timolehto thanks for investigating this.  I will update the demo's to the latest crystal version.

**Comment by timolehto** [comment]
Investigated some more. In the Dockerfile it is set to run `shards update` every time you build the docker image, effectively bypassing the shards frozen in the shard.lock. So if you do development against the docker image there's no telling what version the dependent shards is being used. However shard.lock is in git so one would expect them to work and disregarding shard.lock with docker seems like a terrible idea. If freezing the shards is not wanted then maybe you should just gitignore the shards.lock, which is not without issues either, but for small sample apps with such new language, framework etc. where you'd normally want to stay very bleeding edge it might just be the right thing to do...?

**Comment by drujensen** [comment]
great catch!  I will change the Dockerfile to only install the dependencies instead of update them.

**Comment by drujensen** [comment]
updated Dockerfile to use `crystal deps` instead of `shards update`

**Comment by timolehto** [comment]
Coming from ruby world I find `shards install` or plain `shards` more in analogous to `bundle install` and plain `bundle`, but ymmv. Come to think of it it's rather odd that the crystal guys have so many ways of doing shards install when overall they've been downplaying this ruby philosophy of having multiple ways of doing the same thing e.g. no `Array#collect` in crystal, but for installing deps they have introduced yet another way of doing it `crystal deps`.

Anyhow, good stuff. Cheers
